"""Top-level orchestrator. Run with:

    python -m src.research.feature_importance.run_research

Phases (each is resumable -- caches checked before work):
    1. Statcast pull (years 2022–2025), per-chunk parquet
    2. Build labeled batter-game dataset
    3. Train logreg + LightGBM for variants A, B, C
    4. Compute importance / SHAP / univariate AUC / correlations
    5. Write research_report.md

Pass `--skip-pull` to assume chunks are already on disk (useful for dev iteration).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

from src.research.feature_importance import progress
from src.research.feature_importance.analyze import (
    bat_speed_availability,
    correlation_matrix,
    lgbm_three_way_importance,
    logreg_coef_magnitudes,
    univariate_auc,
)
from src.research.feature_importance.build_dataset import build as build_dataset
from src.research.feature_importance.config import (
    REPORT_PATH,
    SHAP_SAMPLE_SIZE,
    YEARS_ALL,
    YEARS_TEST,
    YEARS_TRAIN,
    all_features_variant_c,
)
from src.research.feature_importance.pull_data import pull_all
from src.research.feature_importance.train_models import (
    VARIANT_DESCRIPTIONS,
    VARIANTS,
    train_all,
    _encode,
)


# ---------------------------------------------------------------------------
# Report writer
# ---------------------------------------------------------------------------

def _write_report(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    results,
    lgbm_imp_C,
    logreg_coefs_C,
    univar,
    corr,
    bat_speed_stats,
    output_path: Path,
) -> None:
    progress.info(f"writing {output_path}")
    lines: list[str] = []
    lines.append("# Feature Importance Research Report")
    lines.append("")
    lines.append(f"_Generated by_ `src.research.feature_importance.run_research`")
    lines.append("")
    lines.append("## Scope")
    lines.append(f"- Train years: **{list(YEARS_TRAIN)}**  ({len(train_df):,} batter-game rows)")
    lines.append(f"- Test (holdout): **{list(YEARS_TEST)}**  ({len(test_df):,} batter-game rows)")
    lines.append(f"- HR rate (label=1): train={train_df['label'].mean():.4f}  test={test_df['label'].mean():.4f}")
    lines.append(f"- Filters applied: starter (PA >= 2 in game) + career_pa >= 100 as of game start")
    lines.append("")
    lines.append("### bat_speed availability")
    for k, v in bat_speed_stats.items():
        lines.append(f"- `{k}`: {v:.1%}")
    lines.append("")

    # Headline ablation
    lines.append("## Ablation -- AUC and log-loss on holdout")
    lines.append("")
    lines.append("| Variant | Description | Model | AUC ^ | Log-loss v |")
    lines.append("|---|---|---|---|---|")
    for r in results:
        lines.append(
            f"| {r.variant} | {VARIANT_DESCRIPTIONS[r.variant]} | "
            f"{r.model_name} | {r.auc:.4f} | {r.log_loss:.4f} |"
        )
    lines.append("")

    # LightGBM 3-way importance for variant C
    lines.append("## LightGBM importance -- variant C (gain · split · mean |SHAP|)")
    lines.append("")
    lines.append(
        f"SHAP computed on a random sample of {SHAP_SAMPLE_SIZE:,} holdout rows "
        "(random_state fixed). `disagreement` = max-rank − min-rank across the three "
        "rankings. Disagreement >= 5 is flagged as an unstable usage signal."
    )
    lines.append("")
    lines.append("| Feature | Gain | Split | Mean \\|SHAP\\| | Rank gain | Rank split | Rank SHAP | Disagree |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    for imp in sorted(lgbm_imp_C, key=lambda x: x.mean_abs_shap, reverse=True):
        flag = " !!" if imp.disagreement >= 5 else ""
        lines.append(
            f"| `{imp.feature}` | {imp.gain:.1f} | {imp.split} | "
            f"{imp.mean_abs_shap:.4f} | {imp.rank_gain} | {imp.rank_split} | "
            f"{imp.rank_shap} | {imp.disagreement}{flag} |"
        )
    lines.append("")

    # Logistic regression coefficients
    lines.append("## Logistic regression coefficients -- variant C (standardized)")
    lines.append("")
    lines.append("| Feature | Coefficient | \\|Coef\\| |")
    lines.append("|---|---:|---:|")
    for _, row in logreg_coefs_C.iterrows():
        lines.append(f"| `{row['feature']}` | {row['coef']:+.4f} | {row['abs_coef']:.4f} |")
    lines.append("")

    # Univariate AUC
    lines.append("## Univariate AUC -- each feature alone")
    lines.append("")
    lines.append("| Feature | Univariate AUC |")
    lines.append("|---|---:|")
    for _, row in univar.iterrows():
        auc = row["univariate_auc"]
        lines.append(f"| `{row['feature']}` | {auc:.4f}" + (" |" if pd.notna(auc) else " (failed) |"))
    lines.append("")

    # High-univariate / low-LGBM-importance flags
    if lgbm_imp_C:
        imp_df = pd.DataFrame([imp.__dict__ for imp in lgbm_imp_C])
        merged = univar.merge(imp_df[["feature", "rank_shap"]], on="feature", how="left")
        flag_rows = merged[
            (merged["univariate_auc"] >= merged["univariate_auc"].quantile(0.75))
            & (merged["rank_shap"] >= len(merged) * 0.5)
        ]
        if len(flag_rows):
            lines.append("## Redundancy flags -- high univariate AUC, low LightGBM rank")
            lines.append("")
            lines.append("These features have predictive power on their own but the model "
                         "barely uses them -- they're likely redundant with other features "
                         "already in the model. Candidates to drop.")
            lines.append("")
            lines.append("| Feature | Univariate AUC | Rank SHAP |")
            lines.append("|---|---:|---:|")
            for _, row in flag_rows.iterrows():
                lines.append(f"| `{row['feature']}` | {row['univariate_auc']:.4f} | {int(row['rank_shap'])} |")
            lines.append("")

    # Mismatch note for variant B
    lines.append("## !! Variant B vs production breakout.py -- name mismatch")
    lines.append("")
    lines.append("Variant B uses **{barrel, sweet_spot, pull_air, max_ev}** per the spec, but "
                 "the production `breakout.py` actually computes breakout from "
                 "**{xwobacon, barrel, hardhit, avg_ev}**. The two sets overlap on `barrel` "
                 "only. Decide which set you want before tuning weights -- the variant-B numbers "
                 "above measure the *spec* set, not the *implemented* set.")
    lines.append("")

    # Correlation matrix (compact)
    lines.append("## Correlation matrix (variant C features)")
    lines.append("")
    lines.append("Pearson correlation. |r| >= 0.7 marked with `**` to flag redundancy.")
    lines.append("")
    cols = [c for c in corr.columns if c in all_features_variant_c()]
    sub = corr.loc[cols, cols]
    lines.append("| | " + " | ".join(f"`{c}`" for c in sub.columns) + " |")
    lines.append("|" + "|".join(["---:"] * (len(sub.columns) + 1)) + "|")
    for idx in sub.index:
        cells = []
        for c in sub.columns:
            v = sub.loc[idx, c]
            mark = "**" if (idx != c and abs(v) >= 0.7) else ""
            cells.append(f"{mark}{v:+.2f}{mark}")
        lines.append(f"| `{idx}` | " + " | ".join(cells) + " |")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    progress.info(f"  -> {output_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Feature-importance research orchestrator."
    )
    parser.add_argument("--skip-pull", action="store_true",
                        help="Skip the Statcast pull (assume chunks already cached).")
    parser.add_argument("--shap-sample", type=int, default=SHAP_SAMPLE_SIZE,
                        help=f"SHAP subsample size (default: {SHAP_SAMPLE_SIZE:,}).")
    args = parser.parse_args()

    progress.banner(f"Feature-importance research starting (years {YEARS_ALL})")

    # 1. Pull
    if not args.skip_pull:
        pull_all(YEARS_ALL)
    else:
        progress.info("skipping Statcast pull (--skip-pull)")

    # 2. Build dataset
    with progress.phase("dataset construction"):
        train_df, test_df = build_dataset()

    # 3. Train
    with progress.phase("model training (3 variants x 2 models)"):
        results = train_all(train_df, test_df)

    # 4. Analyze (variant C is where importance reads matter most)
    with progress.phase("analysis: importance / SHAP / univariate AUC / correlations"):
        feats_C = VARIANTS["C"]
        X_test_C = _encode(test_df, feats_C)
        lgbm_imp_C = lgbm_three_way_importance(
            "C", X_test_C, feats_C, shap_sample_size=args.shap_sample,
        )
        logreg_coefs_C = logreg_coef_magnitudes("C", feats_C)
        univar = univariate_auc(train_df, test_df, feats_C)
        corr = correlation_matrix(train_df, feats_C)
        bs_stats = bat_speed_availability(train_df, test_df)

    # 5. Report
    with progress.phase("write research_report.md"):
        _write_report(
            train_df, test_df, results,
            lgbm_imp_C, logreg_coefs_C, univar, corr, bs_stats,
            REPORT_PATH,
        )

    progress.script_done(f"report: {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
